// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cineweb_movies_api.Context;

namespace cineweb_movies_api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221105224154_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("cineweb_movies_api.Entities.Filme", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("varbinary(16)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HomeMovie")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("Poster")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("filme");
                });

            modelBuilder.Entity("cineweb_movies_api.Entities.Ingresso", b =>
                {
                    b.Property<int>("IdIngresso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte[]>("filme")
                        .HasColumnType("varbinary(16)");

                    b.HasKey("IdIngresso");

                    b.HasIndex("filme");

                    b.ToTable("ingresso");
                });

            modelBuilder.Entity("cineweb_movies_api.Entities.IngressoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("filme")
                        .HasColumnType("varbinary(16)");

                    b.Property<int?>("ingresso")
                        .HasColumnType("int");

                    b.Property<int?>("pedido")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("filme");

                    b.HasIndex("ingresso");

                    b.HasIndex("pedido");

                    b.ToTable("ingresso_pedido");
                });

            modelBuilder.Entity("cineweb_movies_api.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("pedido");
                });

            modelBuilder.Entity("cineweb_movies_api.Entities.Ingresso", b =>
                {
                    b.HasOne("cineweb_movies_api.Entities.Filme", "Filme")
                        .WithMany()
                        .HasForeignKey("filme");

                    b.Navigation("Filme");
                });

            modelBuilder.Entity("cineweb_movies_api.Entities.IngressoPedido", b =>
                {
                    b.HasOne("cineweb_movies_api.Entities.Filme", "Filme")
                        .WithMany()
                        .HasForeignKey("filme");

                    b.HasOne("cineweb_movies_api.Entities.Ingresso", "Ingresso")
                        .WithMany()
                        .HasForeignKey("ingresso");

                    b.HasOne("cineweb_movies_api.Entities.Pedido", "Pedido")
                        .WithMany("Ingressos")
                        .HasForeignKey("pedido");

                    b.Navigation("Filme");

                    b.Navigation("Ingresso");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("cineweb_movies_api.Entities.Pedido", b =>
                {
                    b.Navigation("Ingressos");
                });
#pragma warning restore 612, 618
        }
    }
}
